# --------------------------------------  
# Hexo Butterfly Theme Configuration  
# --------------------------------------  

# --------------------------------------  
# Navigation Settings  
# --------------------------------------  
nav:  
  logo:   
  display_title: true  
  fixed: true  

menu:  
  Archives: /archives/ || fas fa-archive  
  Thinkwave-AI: https://ugly-alpha.vercel.app/ || fas fa-robot  

# --------------------------------------  
# Code Blocks Settings  
# --------------------------------------  
code_blocks:  
  theme: ocean  
  macStyle: true  
  height_limit: 400  
  word_wrap: true  
  copy: true  
  language: true  
  shrink: true  
  fullpage: false  

# Social media links  
social:  
  fab fa-github: https://github.com/luqi-glory || Github || '#24292e'  
  fas fa-envelope: mailto:luqiglory@gmail.com || Email || '#4a7dbe'  

# --------------------------------------  
# Image Settings  
# --------------------------------------  
favicon: /img/lq.jpg  

avatar:  
  img: /img/hack.jpg  
  effect: false  

disable_top_img: false  

default_top_img: /img/hack.jpg  
background_img: /img/hack.jpg  

index_img: /img/hack.jpg  
archive_img: /img/hack.jpg  

footer_img: /img/hack.jpg  

background: "url('/img/hack.jpg') no-repeat center center fixed"  
background_size: cover  

cover:  
  index_enable: true  
  aside_enable: true  
  archives_enable: true  
  default_cover: []  

error_img:  
  flink: /img/friend_404.gif  
  post_page: /img/hack.jpg  

error_404:  
  enable: true  
  subtitle: 'Oops! 页面走丢了'  
  background: /img/lq.jpg  

post_meta:  
  page:  
    date_type: created  
    date_format: date  
    label: true  
  post:  
    position: center  
    date_type: both  
    date_format: date  
    label: true  

# --------------------------------------  
# Index page settings  
# --------------------------------------  
index_site_info_top: 50%  
index_top_img_height: 400px  

subtitle:  
  enable: true  
  effect: true  
  typed_option:  
    typeSpeed: 50  
  source: false  
  sub:  
    - "思如潮浪"  
    - "Embrace your waves of thought"  

index_layout: 4  

index_post_content:  
  method: 3  
  length: 300  

# --------------------------------------  
# Post Settings  
# --------------------------------------  
toc:  
  post: true  
  page: false  
  number: true  
  expand: true  
  style_simple: false  
  scroll_percent: true  

post_copyright:  
  enable: true  
  decode: false  
  author_href: https://yourwebsite.com  
  license: CC BY-NC-SA 4.0  
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/  

reward:  
  enable: false  

post_edit:  
  enable: false  

related_post:  
  enable: true  
  limit: 6  
  date_type: created  

post_pagination: 1  

noticeOutdate:  
  enable: true  
  style: flat  
  limit_day: 365  
  position: top  
  message_prev: "本文已超过"  
  message_next: "未更新，可能已过时。"  

# --------------------------------------  
# Footer Settings  
# --------------------------------------  
footer:  
  owner:  
    enable: true  
    since: 2019  
  custom_text: "Powered by Love & Coffee"  
  copyright: true  

# --------------------------------------  
# Aside Settings  
# --------------------------------------  
aside:  
  enable: true  
  hide: false  
  button: true  
  mobile: true  
  position: right  
  display:  
    archive: true  # 保留归档功能  
  card_author:  
    enable: true  
    description: "一个热爱代码与生活的家伙"  
    button:  
      enable: true  
      icon: fab fa-github  
      text: "访问我的 GitHub"  
      link: https://github.com/luqi-glory 
  card_announcement:  
    enable: true  
    content: "欢迎体验我的新作品！"  
  card_recent_post:  
    enable: true  
    limit: 5  
    sort: date  
  card_archives:  
    enable: true  
    type: monthly  
    format: MMMM YYYY  
    order: -1  
    limit: 8  
  card_webinfo:  
    enable: true  
    post_count: true  
    last_push_date: true 

# --------------------------------------  
# Bottom right button  
# --------------------------------------  
rightside_bottom: 20px  

translate:  
  enable: false  

readmode: true  

darkmode:  
  enable: true  
  button: true  
  autoChangeMode: 1  

rightside_scroll_percent: false  

# --------------------------------------  
# Global Settings  
# --------------------------------------  
anchor:  
  auto_update: true  
  click_to_scroll: true  

photofigcaption: true  

copy:  
  enable: true  
  copyright:  
    enable: true  
    limit_count: 100  

wordcount:  
  enable: true  
  post_wordcount: true  
  min2read: true  
  total_wordcount: true  

busuanzi:  
  site_uv: true  
  site_pv: true  
  page_pv: false  

# --------------------------------------  
# Math  
# --------------------------------------  
math:  
  use: katex  
  per_page: false  

# --------------------------------------  
# Search  
# --------------------------------------  
search:  
  use: local_search  
  placeholder: "搜索我的世界..."  

local_search:  
  preload: true  
  top_n_per_article: 1  
  unescape: false  

# --------------------------------------  
# Share System  
# --------------------------------------  
share:  
  use: sharejs  
  sharejs:  
    sites: facebook,twitter,weibo,qq  

# --------------------------------------  
# Comments System  
# --------------------------------------  
comments:  
  use: Valine  
  text: true  
  lazyload: false  
  count: true  
  card_post_count: true  

valine:  
  appId:  # 请填入你的 LeanCloud appId  
  appKey:  # 请填入你的 LeanCloud appKey  
  avatar: retro  
  serverURLs:  
  visitor: true  

# --------------------------------------  
# Beautify / Effect  
# --------------------------------------  
theme_color:  
  enable: true  
  main: "#42A5F5"  
  paginator: "#0288D1"  
  button_hover: "#FF5722"  
  text_selection: "#0288D1"  
  link_color: "#1976D2"  
  meta_color: "#757575"  
  hr_color: "#B0BEC5"  
  code_foreground: "#EF5350"  
  code_background: "#ECEFF1"  
  toc_color: "#0288D1"  
  blockquote_padding_color: "#42A5F5"  
  blockquote_background_color: "#E3F2FD"  
  scrollbar_color: "#42A5F5"  
  meta_theme_color_light: "#FFFFFF"  
  meta_theme_color_dark: "#212121"  

category_ui: index  
tag_ui: index  

rounded_corners_ui: true  

text_align_justify: true  

mask:  
  header: true  
  footer: true  

preloader:  
  enable: true  
  source: 2  
  pace_css_url: https://cdn.jsdelivr.net/npm/pace-js@latest/pace.min.js  

enter_transitions: true  

display_mode: light  

# --------------------------------------  
# Lightbox Settings  
# --------------------------------------  
lightbox: fancybox  

# --------------------------------------  
# Other Settings  
# --------------------------------------  
inject:  
  head:  
    - <meta name="description" content="我的 Hexo 博客，分享生活与技术">  
  bottom:  
    - |  
      <script>  
        document.addEventListener('DOMContentLoaded', function() {  
          fetch('/ai-chat.js')  
            .then(res => res.json())  
            .then(data => console.log('AI返回的数据：', data))  
            .catch(err => console.error('调用 AI 接口失败：', err));  
        });  
      </script>